CREATE TABLE films (
id BIGINT GENERATED BY DEFAULT AS PRIMARY KEY ,
name VARCHAR NOT NULL,
description TEXT NOT NULL,
release_date DATE,
duration INT,
mpa_id INTEGER,
FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id),
)

CREATE TABLE mpa (
mpa_id INTEGER NOT NULL PRIMARY KEY,
mpa_name VARCHAR(10) NOT NULL UNIQUE
)

CREATE TABLE genres (
genre_id INTEGER NOT NULL PRIMARY KEY,
genre_name VARCHAR(10) NOT NULL UNIQUE
)

CREATE TABLE film_genres (
film_id BIGINT NOT NULL,
genre_id INTEGER NOT NULL,
PRIMARY KEY (film_id, genre_id),
FOREIGN KEY (film_id) REFERENCES films(id),
FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
)

CREATE TABLE film_likes(
film_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
PRIMARY KEY (user_id, film_id),
FOREIGN KEY (film_id) REFERENCES films(id),
FOREIGN KEY (user_id) REFERENCES users(id)
)

CREATE TABLE users(
id BIGINT GENERATED BY DEFAULT AS PRIMARY KEY,
email VARCHAR NOT NULL,
login VARCHAR NOT NULL,
name VARCHAR NOT NULL,
birthday DATE,
)

CREATE TABLE friendships(
user_id BIGINT NOT NULL,
friend_id BIGINT,
status VARCHAR,
PRIMARY KEY (user_id, friend_id),
FOREIGN KEY (user_id) REFERENCES users(id)
)

